# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - binary: bay
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
release:
  header: |
    ## Bay CLI (v{{.Version}})
    ### Installation via Brew
    The preferred method is installation via [Homebrew](https://brew.sh/).
    ```
    brew tap dpc-sdp/bay-cli
    brew install bay-cli
    ```

archives:
  - id: binaries
    builds:
      - lagoon
    format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    files:
      - none*
  - id: binaries-targz
    builds:
      - lagoon
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# .goreleaser.yaml
brews:
  - name: bay-cli
    tap:
      owner: dpc-sdp
      name: homebrew-bay-cli
    homepage: "https://github.com/dpc-sdp/bay-cli"
    ids: []
    goarm: 6
    goamd64: v1
    commit_author:
      name: SDP Deploy
      email: de.ops@dpc.vic.gov.au
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    description: "CLI tool to interact with the Bay container platform"

    # Folder inside the repository to put the formula.
    folder: Formula

    # SPDX identifier of your app's license.
    license: "MIT"
    skip_upload: false
